#pragma once

#include <map>
#include <string>
#include <cstdint>

namespace ss {
  enum class DashboardIcon : uint8_t {
    DataGrid,
    MultiPlot,
    Accelerometer,
    Gyroscope,
    GPS,
    FFT,
    LED,
    Plot,
    Bar,
    Gauge,
    Compass,
    Terminal,
    Plot3D,
    NoWidget
};

const std::map<DashboardIcon, std::string> DashboardIconMap = {
    {DashboardIcon::DataGrid, "datagrid.svg"},
    {DashboardIcon::MultiPlot, "multiplot.svg"},
    {DashboardIcon::Accelerometer, "accelerometer.svg"},
    {DashboardIcon::Gyroscope, "gyroscope.svg"},
    {DashboardIcon::GPS, "gps.svg"},
    {DashboardIcon::FFT, "fft.svg"},
    {DashboardIcon::LED, "led.svg"},
    {DashboardIcon::Plot, "plot.svg"},
    {DashboardIcon::Bar, "bar.svg"},
    {DashboardIcon::Gauge, "gauge.svg"},
    {DashboardIcon::Compass, "compass.svg"},
    {DashboardIcon::Terminal, "terminal.svg"},
    {DashboardIcon::Plot3D, "plot3d.svg"},
    {DashboardIcon::NoWidget, "group.svg"}
};

enum class ActionIcon : uint8_t {
    Abscissa,
    Accuracy,
    AddProperties,
    Alpha,
    AlphabeticalSorting,
    America,
    AngryFaceMeme,
    AtmosphericPressure,
    AudioCable,
    Azimuth,
    BatteryLevel,
    Beta,
    BinaryFile,
    Bluetooth,
    Capacitor,
    CellularNetwork,
    Close,
    CloudLightning,
    Clouds,
    CodeFork,
    Code,
    Comparator,
    Connected,
    Counter,
    Cursor,
    DataTransfer,
    DeleteDocument,
    DewPoint,
    Disconnected,
    Display,
    Done,
    EditProperty,
    Edit,
    Electricity,
    Erase,
    FuturamaBender,
    Gamma,
    Gears,
    Geometry,
    GPSAntenna,
    GPSDisconnected,
    GPSSignal,
    GroundSymbol,
    Gyroscope,
    Hammer,
    Home,
    HomerSimpson,
    Idea,
    ImportantProperty,
    InfraredSensor,
    Infrared,
    Jewel,
    Ladder,
    Lambda,
    LEDDiode,
    Length,
    Lock,
    MatrixDesktop,
    MotionSensor,
    Mu,
    Omega,
    OrthogonalView,
    Oscillator,
    Padlock,
    Pause,
    Pi,
    PlayGraphReport,
    PlayProperty,
    Play,
    Plot,
    Potentiometer,
    Processor,
    ProjectSetup,
    PropertiesScript,
    ProximitySensor,
    Radar,
    Relay,
    Resistor,
    Restart,
    RoboticArm,
    SatelliteSignal,
    ScaredFaceMeme,
    SearchProperty,
    Sensor,
    Services,
    ShowProperty,
    Shuffle,
    Shutdown,
    Sigma,
    Signal,
    SleepMode,
    Slider,
    StopProperty,
    Stop,
    SystemTask,
    Toolbox,
    Transistor,
    UploadToTheCloud,
    UrgentProperty,
    WindGauge,
    Windsock,
    Workflow,
    XboxA,
    XboxB,
    XboxX,
    XboxY,
    ZoomIn,
    ZoomOut,
};

const std::map<ActionIcon, std::string> ActionIconMap = {
    {ActionIcon::Abscissa, "Abscissa"}  ,
    {ActionIcon::Accuracy, "Accuracy"},
    {ActionIcon::AddProperties, "Add properties"},
    {ActionIcon::Alpha, "Alpha"},
    {ActionIcon::AlphabeticalSorting, "Alphabetical Sorting"},
    {ActionIcon::America, "America"},
    {ActionIcon::AngryFaceMeme, "Angry Face Meme"},
    {ActionIcon::AtmosphericPressure, "Atmospheric Pressure"},
    {ActionIcon::AudioCable, "Audio Cable"},
    {ActionIcon::Azimuth, "Azimuth"},
    {ActionIcon::BatteryLevel, "Battery Level"},
    {ActionIcon::Beta, "Beta"},
    {ActionIcon::BinaryFile, "Binary File"},
    {ActionIcon::Bluetooth, "Bluetooth"},
    {ActionIcon::Capacitor, "Capacitor"},
    {ActionIcon::CellularNetwork, "Cellular Network"},
    {ActionIcon::Close, "Close"},
    {ActionIcon::CloudLightning, "Cloud Lightning"},
    {ActionIcon::Clouds, "Clouds"},
    {ActionIcon::CodeFork, "Code Fork"},
    {ActionIcon::Code, "Code"},
    {ActionIcon::Comparator, "Comparator"},
    {ActionIcon::Connected, "Connected"},
    {ActionIcon::Counter, "Counter"},
    {ActionIcon::Cursor, "Cursor"},
    {ActionIcon::DataTransfer, "Data Transfer"},
    {ActionIcon::DeleteDocument, "Delete Document"},
    {ActionIcon::DewPoint, "Dew Point"},
    {ActionIcon::Disconnected, "Disconnected"},
    {ActionIcon::Display, "Display"},
    {ActionIcon::Done, "Done"},
    {ActionIcon::EditProperty, "Edit Property"},
    {ActionIcon::Edit, "Edit"},
    {ActionIcon::Electricity, "Electricity"},
    {ActionIcon::Erase, "Erase"},
    {ActionIcon::FuturamaBender, "Futurama Bender"},
    {ActionIcon::Gamma, "Gamma"},
    {ActionIcon::Gears, "Gears"},
    {ActionIcon::Geometry, "Geometry"},
    {ActionIcon::GPSAntenna, "GPS Antenna"},
    {ActionIcon::GPSDisconnected, "GPS Disconnected"},
    {ActionIcon::GPSSignal, "GPS Signal"},
    {ActionIcon::GroundSymbol, "Ground Symbol"},
    {ActionIcon::Gyroscope, "Gyroscope"},
    {ActionIcon::Hammer, "Hammer"},
    {ActionIcon::Home, "Home"},
    {ActionIcon::HomerSimpson, "Homer Simpson"},
    {ActionIcon::Idea, "Idea"},
    {ActionIcon::ImportantProperty, "Important Property"},
    {ActionIcon::InfraredSensor, "Infrared Sensor"},
    {ActionIcon::Infrared, "Infrared"},
    {ActionIcon::Jewel, "Jewel"},
    {ActionIcon::Ladder, "Ladder"},
    {ActionIcon::Lambda, "Lambda"},
    {ActionIcon::LEDDiode, "LED Diode"},
    {ActionIcon::Length, "Length"},
    {ActionIcon::Lock, "Lock"},
    {ActionIcon::MatrixDesktop, "Matrix Desktop"},
    {ActionIcon::MotionSensor, "Motion Sensor"},
    {ActionIcon::Mu, "Mu"},
    {ActionIcon::Omega, "Omega"},
    {ActionIcon::OrthogonalView, "Orthogonal View"},
    {ActionIcon::Oscillator, "Oscillator"},
    {ActionIcon::Padlock, "Padlock"},
    {ActionIcon::Pause, "Pause"},
    {ActionIcon::Pi, "Pi"},
    {ActionIcon::PlayGraphReport, "Play Graph Report"},
    {ActionIcon::PlayProperty, "Play Property"},
    {ActionIcon::Play, "Play"},
    {ActionIcon::Plot, "Plot"},
    {ActionIcon::Potentiometer, "Potentiometer"},
    {ActionIcon::Processor, "Processor"},
    {ActionIcon::ProjectSetup, "Project Setup"},
    {ActionIcon::PropertiesScript, "Properties Script"},
    {ActionIcon::ProximitySensor, "Proximity Sensor"},
    {ActionIcon::Radar, "Radar"},
    {ActionIcon::Relay, "Relay"},
    {ActionIcon::Resistor, "Resistor"},
    {ActionIcon::Restart, "Restart"},
    {ActionIcon::RoboticArm, "Robotic Arm"},
    {ActionIcon::SatelliteSignal, "Satellite Signal"},
    {ActionIcon::ScaredFaceMeme, "Scared Face Meme"},
    {ActionIcon::SearchProperty, "Search Property"},
    {ActionIcon::Sensor, "Sensor"},
    {ActionIcon::Services, "Services"},
    {ActionIcon::ShowProperty, "Show Property"},
    {ActionIcon::Shuffle, "Shuffle"},
    {ActionIcon::Shutdown, "Shutdown"},
    {ActionIcon::Sigma, "Sigma"},
    {ActionIcon::Signal, "Signal"},
    {ActionIcon::SleepMode, "Sleep Mode"},
    {ActionIcon::Slider, "Slider"},
    {ActionIcon::StopProperty, "Stop Property"},
    {ActionIcon::Stop, "Stop"},
    {ActionIcon::SystemTask, "System Task"},
    {ActionIcon::Toolbox, "Toolbox"},
    {ActionIcon::Transistor, "Transistor"},
    {ActionIcon::UploadToTheCloud, "Upload to the Cloud"},
    {ActionIcon::UrgentProperty, "Urgent Property"},
    {ActionIcon::WindGauge, "Wind Gauge"},
    {ActionIcon::Windsock, "Windsock"},
    {ActionIcon::Workflow, "Workflow"},
    {ActionIcon::XboxA, "Xbox A"},
    {ActionIcon::XboxB, "Xbox B"},
    {ActionIcon::XboxX, "Xbox X"},
    {ActionIcon::XboxY, "Xbox Y"},
    {ActionIcon::ZoomIn, "Zoom In"},
    {ActionIcon::ZoomOut, "Zoom Out"},
};
}